### ISSUE TITLE
v0.2.0 Complete related milestones

### ISSUE THREAD

**Issue by mkungla** [howijd/howijd.network#101]
### Acceptance

Close related milestones

### The Abstract

Close related milestones

### Tasks

- [x] https://github.com/howijd/howijd.com/milestone/2
- [x] https://github.com/howijd/howi/milestone/1
- [x] https://github.com/howijd/howijd.org/milestone/2
- [x] https://github.com/howijd/.github/milestone/1
- [x] https://github.com/howijd/howijd/milestone/1

### Resources

| resources | description |
| --- | --- |
| ... | ... |
