### ISSUE TITLE
v0.3.0 Complete related milestones

### ISSUE THREAD

**Issue by mkungla** [howijd/howijd.network#103]
### Acceptance

Complete related milestones

### The Abstract

Complete related milestones

### Tasks

- [x] https://github.com/howijd/howijd/milestone/2
- [x] https://github.com/howijd/howijd.com/milestone/3
- [x] https://github.com/howijd/howi/milestone/3
- [x] https://github.com/howijd/howijd.org/milestone/3
- [x] https://github.com/howijd/.github/milestone/3

### Resources

| resources | description |
| --- | --- |
| ... | ... |
