### ISSUE TITLE
Deployment of the Howijd Devel/Releaser Addon

### ISSUE THREAD

**Issue by mkungla** [howijd/howijd.network#143]
### Acceptance

Devel/Releaser produces successful network upgrades and releases

### The Abstract

**The Howijd Devel/Releaser Addon is an advanced Addon that deploys a complex workflow containing in-chain, off-chain, and cross-chain interactions. This addon showcases some of the advanced capabilities of the Howijd.Network platform.**

The Devel/Releaser Addon executes a release based on workflow definition defined in addon that includes several key phases:

- **Preparation:** tasks such as setting up the necessary infrastructure, preparing assets, and creating changelogs are performed.
- **Build:** the source code is compiled and the necessary binaries are created.
- **Release:** relevant transactions are created, the network upgrade is published, and platform-specific packages are bundled.
- **Publish:** public resources are updated and the latest version is published to platform-specific off-chain destinations such as GitHub.
- **Clean:** any resources that are no longer needed are cleaned up.
- **Verify:** checks for integrity and analyzes the released packages to ensure the release is successful.

The Devel/Releaser Addon is designed to be a proof of concept for Howijd.Network Addons, which can bridge off-chain and on-chain functionality. This allows the addon to perform a wide range of tasks, including interacting with off-chain systems and APIs and committing actions to off-chain services. 

The target execution time for this workflow is 600 seconds, 
highlighting the network's extreme performance capabilities.

### Tasks

- [ ] deploy it to network
- [ ] monitor addons performance over at least one full release cycle
- [ ] plan handover procedure to DAO and disposing of the add when mainnet is operational and DAO can take over the release managment.

**Comment by howibot** [comment]
This is a new comment.

**Comment by howibot** [comment]
**released:** *v0.4.25*
**elapsed:** *1m27.007367298s*

**Comment by howibot** [comment]
**released:** *v0.4.26*
**elapsed:** *1m12.756960702s*
**memory usage:** *1476.69 MiB*
