### ISSUE TITLE
Okram era

### ISSUE THREAD

**Issue by mkungla** [howijd/howijd.network#20]
### Slogan or tagline

Foundation of howijd.network

### Version

1.0.0

### Start:

in-progress

### Release date:

30.08.2024

### Discussions:

https://github.com/howijd/howijd.network/discussions/categories/era-okram

### Previous era:

research and development 2011 - 2021 

### The Abstract

...

### Milestones

**Following primary milestones are part of Okram Era development.**
 
**Q3 2021**

- [ ] v0.1.0 - Community health

**Q4 2021**

- [ ] v0.2.0 - Foundation and infrastructure implementation

**Q1 2022**

- [ ] v0.3.0 - Network Components

**Q2 2022**

- [ ] v0.4.0 - HOWI Genesis Chain

**Q3 2022**

- [ ] v0.5.0 - Smart Contracts between internal core components

**Q4 2022**

- [ ] v0.6.0 - User Interfaces for v1  

**Q1 2023**

- [ ] v0.7.0 - Decentralization of resource handles

**Q2 2023**

- [ ] v0.8.0 - API beta, libraries and consumer smart contracts

**Q3 2023**

- [ ] v0.9.0 - API v1 lock-down

**Q4 2023**

- [ ] v0.10.0 - Decentralization of core components

**Q1 2024**

- [ ] v1.0.0-alpha - Security audit
- [ ] v1.0.0-beta - Performance benchmark, and load testing
- [ ] v1.0.0-c -  Marketing

**Q1 2024**

- [ ] v1.0.0-d - Public beta
- [ ] v1.0.0-e - Quality assurance 

**Q2 2024**

- [ ] v1.0.0-rc - Community requests and last minute feature voting.  
- [ ] v1.0.0-rc.1 - Community engagement phase 1 
- [ ] v1.0.0-rc.2 - Community engagement phase 2 

**Q3 2024**

- [ ] v1.0.0 - Okram Era release 

### Resources

| resources | description |
| --- | --- |
| [howijd.network] | Howijd.Network website your primary source of information. |
| [lowijd.org] | Howijd.Network Community resources, docs and learning materials |
| [howijd.com] | Resources using Howijd.Network with your commercial products. |
| [github.com/howijd] | Howijd.Network GitHub repositories |

[howijd.network]: https://howijd.network
[lowijd.org]: https://howijd.org
[howijd.com]: https://howijd.com
[github.com/howijd]: https://github.com/howijd
