### ISSUE TITLE
 v0.1.0 - Community health

### ISSUE THREAD

**Issue by mkungla** [howijd/howijd.network#23]
![howijd.network](https://raw.githubusercontent.com/howijd/howijd.network/main/assets/images/howijd/src/howijd-full.svg)

### Version

0.1.0

### Objective

Community health

### Start:

2021

### Release date:

https://github.com/howijd/howijd.network/milestone/2

### Discussions:

https://github.com/howijd/howijd.network/discussions/22

### The Abstract

...

### Stories

- [x] #65
- [x] #66

### Tasks

- [x] #2 
- [x] #3 
- [x] #4
- [x] #8
- [x] #9
- [x] #11
- [x] #16
- [x] #24
- [x] #29
- [x] #67 
- [x] #68
- [ ] howijd/howijd.org/issues/9
- [ ] howijd/howijd.com/issues/9
- [x] #70
- [x] #82
- [x] #83
- [x] #84

**howijd/howijd.org**

- [x] https://github.com/howijd/howijd.org/issues/1

**howijd/howijd.com**
- [x] https://github.com/howijd/howijd.com/issues/2

### Resources

| resources | description |
| --- | --- |
| ... | ... |
