### ISSUE TITLE
v0.2.0 - Foundation and infrastructure implementation

### ISSUE THREAD

**Issue by mkungla** [howijd/howijd.network#28]
### Version

0.2.0

### Objective

Foundation and infrastructure implementation

### Start:

Q4 2021

### Release date:

https://github.com/howijd/howijd.network/milestone/3

### Discussions:

https://github.com/howijd/howijd.network/discussions/27

### The Abstract

...

### Stories

- [x] #122
- [x] howijd/howijd.network#140
- [x] howijd/howijd.network#121
- [x] howijd/howijd.network#101

### Tasks

- [x] https://github.com/howijd/.github/issues/130
- [x] https://github.com/howijd/.github/issues/131
- [x] howijd/howijd.network#141
- [x] https://github.com/howijd/.github/issues/128
- [x] https://github.com/howijd/howijd/issues/2
- [x] https://github.com/howijd/howijd/issues/1
- [x] https://github.com/howijd/howijd.network/issues/97
- [x] https://github.com/howijd/howijd/issues/4
- [x] https://github.com/howijd/howijd/issues/6
- [x] https://github.com/howijd/howijd.network/issues/102
- [x] https://github.com/howijd/.github/issues/133
- [x] https://github.com/howijd/howijd/issues/7
- [x] https://github.com/howijd/howijd/issues/8
- [x] https://github.com/howijd/howijd/issues/9
- [x] https://github.com/howijd/howijd/issues/10
- [x] https://github.com/howijd/howijd/issues/14
- [x] https://github.com/howijd/howijd/issues/52
- [x] https://github.com/howijd/howijd/issues/15
- [x] https://github.com/howijd/howijd/issues/18
- [x] howijd/howijd.network#138
- [x] https://github.com/howijd/howijd.network/issues/121
- [x] https://github.com/howijd/howijd/issues/11
- [x] https://github.com/howijd/howijd/issues/12
- [x] https://github.com/howijd/howijd/issues/13
- [x] howijd/howijd.network#140
- [x] https://github.com/howijd/howijd/issues/20
- [x] https://github.com/howijd/howijd/issues/5
- [x] howijd/howijd.network#139
- [x] https://github.com/howijd/howijd/issues/21
- [x] https://github.com/howijd/howijd.network/issues/122
- [x] https://github.com/howijd/howijd/issues/22
- [x] https://github.com/howijd/howijd/issues/23
- [x] https://github.com/howijd/howijd.network/issues/125
- [x] https://github.com/howijd/howijd/issues/49
- [x] https://github.com/howijd/howijd/issues/50
- [x] https://github.com/howijd/howijd/issues/51
- [x] howijd/howijd#26
- [x] https://github.com/howijd/howijd/issues/19
- [x] https://github.com/howijd/howijd/issues/24
- [x] https://github.com/howijd/howijd/issues/55

### Resources

| resources | description |
| --- | --- |
| ... | ... |
